### ISSUE TITLE
对您的组播很感兴趣

### ISSUE THREAD

**Issue by ykyfy** [redrainl/iptv#3]
大佬 可以写个从  fofa.info 搜索ip的版本吗 那里的比较新

**Comment by redrainl** [comment]
看了一下，感觉用fofa搜的ip可用性也没见得更好，还是tonkiang更方便，毕竟它是专门用于iptv搜索的。

**Comment by ykyfy** [comment]
我看fofa上很多新ip  tonkiang上都没有的 然后江苏的iptv组播   tonkiang上搜索不到的  fofa上有很多

**Comment by ykyfy** [comment]
> 看了一下，感觉用fofa搜的ip可用性也没见得更好，还是tonkiang更方便，毕竟它是专门用于iptv搜索的。

我看fofa上很多新ip都可以播放的， tonkiang上都没有的，还有江苏的iptv组播 tonkiang上搜索不到的 fofa上有很多都可以播放，然后 tonkiang上的ip用的人多 很卡  失效也快

**Comment by redrainl** [comment]
能不能具体说一下你的搜索过程看看，也可能是我的搜索方法不对，试了几个ip都无效。

**Comment by ykyfy** [comment]
> 能不能具体说一下你的搜索过程看看，也可能是我的搜索方法不对，试了几个ip都无效。
https://raw.githubusercontent.com/frxz751113/IPTVzb1/main/组播py/组播综合.py
 你看下他们用的搜索方式  但是他们的不能测速 还是比较喜欢你的版本

**Comment by ykyfy** [comment]
https://github.com/frxz751113/IPTVzb1

**Comment by ykyfy** [comment]
> 能不能具体说一下你的搜索过程看看，也可能是我的搜索方法不对，试了几个ip都无效。

这套江苏电信组播 别人那里复制来的  你进去换几个ip试试看   fofa链接: https://fofa.info/result?qbase64=InVkcHh5IiAmJiBjb3VudHJ5PSJDTiIgJiYgcmVnaW9uPSJKaWFuZ3N1IiAmJiBvcmc9IkNoaW5hbmV0IiAmJiBwcm90b2NvbD0iaHR0cCI%3D
[江苏电信.txt](https://github.com/user-attachments/files/16370671/default.txt)

**Comment by redrainl** [comment]
已新增fofa.sh，生成文件zubo_fofa.txt，江苏电信也加进去了，有几个省的ip没搜到，不确定是频道模板有变化了还是搜索参数要优化，没有仔细，基本能用了。每天和原来的脚本一起定时更新频道列表。

**Comment by ykyfy** [comment]
大神 港澳台的能搞到吗

**Comment by ykyfy** [comment]
同个频道可以排列一起吗

**Comment by redrainl** [comment]
港澳台没有稳定的直播源。同频排列，如果是海川影音之类的播放器，只有去掉分组标记，会自动组合同源，无所谓排序。不同使用者会有不同的习惯，我是习惯按源头地区分组，毕竟每个组里面已经有多套ip了。那么多实际上不用全都要，各取所需就好了。

**Comment by redrainl** [comment]
我现在用的是海川影音，同频道的多个源会自动聚合在一起，不用关心具体位置，看电视时同一频道切换源就可以，否则频道列表就太冗长了，
就是因为txt格式播放列表的这个特点，我才暂时放弃了m3u格式列表，其实m3u的优点也很多。

**Comment by ykyfy** [comment]
> 港澳台没有稳定的直播源。同频排列，如果是海川影音之类的播放器，只有去掉分组标记，会自动组合同源，无所谓排序。不同使用者会有不同的习惯，我是习惯按源头地区分组，毕竟每个组里面已经有多套ip了。那么多实际上不用全都要，各取所需就好了。

广西95的那组 有几个港澳台的 能加进去吗
